### ISSUE TITLE
 How to generate image features using VGGNet?

### ISSUE THREAD

**Issue by 22881916** [wasiahmad/visual_story_telling#3]
Hello Wasiahmad,
Could you tell me how to generate image features using VGG? I don't know how to generate files such as vist_train_image_features.hdf5.
I used the code(https://github.com/tomrunia/TF_FeatureExtraction) to extract image features using vgg_fc7, but it couldn't work in your project.

**Comment by wasiahmad** [comment]
Hi, I have shared the following three files [here](https://drive.google.com/file/d/1WvkHNY6Mp-G0qGV6CATYE_lCDow02EHN/view?usp=sharing).

1. vist_train_image_features.hdf5
2. vist_dev_image_features.hdf5
3. vist_test_image_features.hdf5

Thanks.

**Comment by 22881916** [comment]
Ok, thank you very much.
